### ISSUE TITLE
Youtube Links not working

### ISSUE THREAD

**Issue by TrueMB** [vured/vured-bot#43]
**Describe the bug**
Hello! Before going into the details, I am using the Fork from @AlexAdiaconitei, since I read that this project Owner didnt got much time currently.

I am running the Docker Container on the newest Ubuntu Version and used the docker compose command with my credentials and channel ids. (Spotify wasn't set up)
It seems to load everything correctly. The bots creates the Player Messages and logs getting sent.
![image](https://user-images.githubusercontent.com/25579052/212484546-28f5877e-81fb-4458-809d-db1e276e9c9f.png)
![image](https://user-images.githubusercontent.com/25579052/212484595-4bd0d2dd-1aed-4562-81d1-5a0e214946dd.png)

But for some reason it cannot load youtube songs.
The Bot joins the channel for few seconds and then disconnects, because the playlist is empty.

![image](https://user-images.githubusercontent.com/25579052/212485026-03240c49-f433-471c-8b0a-7019e55a5718.png)

The second Problem is, that the Webinterface isn't starting.

https://pastebin.com/tf5g0h3f

**Comment by AlexAdiaconitei** [comment]
Hello there!
From the screenshots and the logs that you provided everything looks fine. I was thinking that maybe the problem comes from the permissions that the BOT has been given on the Discord Developer Portal. The minimum permissions code is 2150640640 as it includes permission for the BOT to be able to speak on the audio channels. Maybe you can try to re-invite the BOT to your server using this code on the URL generator that the Discord Developer Portal provides. You can also check that the PRESENCE INTENT, SERVER MEMBERS INTENT and MESSAGE CONTENT INTENT are enabled for your BOT.

About the WEB-UI, did you deploy it under https?

Apart from that, are there any logs on the log-channel when you add songs to the playlist?

**Comment by TrueMB** [comment]
I recreated the bot token with the specific permissions, but it still doesn't work. Even with Administration rights.

The intents  are enabled.

And this is the log of the log channel:
![image](https://user-images.githubusercontent.com/25579052/212559374-1624a5f7-9000-4f77-a452-f6c46f32afe1.png)


I never did anything specific to the web ui. Can I change settings for that?
I tested http and https to open.

**Comment by TrueMB** [comment]
Now using another bot.

**Comment by lokzz** [comment]
> Now using another bot.

pls tell me what bot (vured-bot is now giving me 403's everytime)

**Comment by TrueMB** [comment]
I am using a normal music player. In my case **Musico**
